data:
  image: busybox
  command: /bin/true
  volumes:
    - /var/lib/postgresql/data

db:
  image: postgres:9.4
  ports:
    - "5432:5432"
  volumes_from:
    - data
  environment:
    - POSTGRES_DB=plt
    - POSTGRES_USER=plt
    - POSTGRES_PASSWORD=plt

web:
  #build: .
  image: jensfischerhh/plt:latest
  ports:
    - "8080:8080"
  volumes:
    - ~/.m2/repository:/root/.m2/repository
  links:
    - db
  environment:
    - PORT=8080
    - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/plt
    - JDBC_DATABASE_USERNAME=plt
    - JDBC_DATABASE_PASSWORD=plt
  command: ["--spring.jpa.generateDdl=false", "--spring.jpa.showSql=true", "--spring.jpa.hibernate.ddlAuto=validate"]
