info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    name: @project.name@
    description: @project.description@

# APPLICATION SETTINGS (SpringApplication)
spring:
  main:
    web_environment: true
    show_banner: true

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    max-active: 15
    max-idle: 5
    min-idle: 1
    initial-size: 5
    jmx-enabled: true

  h2:
    console:
      enabled: true

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  thymeleaf:
    cache: false

  data:
    rest:
      basePath: api

# FLYWAY (FlywayProperties)
flyway:
  enabled: false


# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: ${port:8080}
  session-timeout: 1800

# MANAGEMENT HTTP SERVER (ManagementServerProperties)
management:
  context-path: /system

endpoints:
  health:
    sensitive: false
  jmx:
    domain: PartyLootTracker
    uniqueNames: false


logging:
  level:
    org.hibernate: 'INFO'
    org.springframework.instrument: 'TRACE'
    org.springframework.boot: 'INFO'
    org.springframework.core: 'INFO'
