spring:
  main:
    show_banner: false

  thymeleaf:
    cache: true

  # https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    removeAbandoned: true
    initialSize: 5
    minIdle: 2
    maxActive: 10
    maxIdle: 5

  h2:
    console:
      enabled: false

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate

flyway:
  enabled: true

endpoints:
  env:
    keys-to-sanitize: password,secret,key,url
