info:
  build:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    name: @project.name@
    description: @project.description@


# APPLICATION SETTINGS (SpringApplication)
spring:
  main:
    web_environment: true
    show_banner: true

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    #url: postgres://plt:plt@localhost:5432/plt
    #username: dbuser
    #password: dbpass
    #driver-class-name: com.mysql.jdbc.Driver
    max-active: 15
    max-idle: 5
    min-idle: 1
    initial-size: 5
    jmx-enabled: true

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false


  # SPRING SOCIAL (SocialWebAutoConfiguration)
  social:
    auto-connection-views: true # Set to true for default connection views or false if you provide your own

    # SPRING SOCIAL FACEBOOK (FacebookAutoConfiguration)
    facebook:
      app-id: ${facebook.app.id:123456789}
      app-secret: ${facebook.app.secret:987654321}

# FLYWAY (FlywayProperties)
flyway:
  enabled: true
  #url: postgres://plt:plt@localhost:5432/plt
  #username: dbuser
  #password: dbpass


# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: ${port:8080}
  session-timeout: 1800

# SECURITY (SecurityProperties)
security:
  require-ssl: false
  enable-csrf: false
  #ignored: /api/hello
  basic:
    realm: Party Loot Tracker
  user:
    name: admin
    password: password


# MANAGEMENT HTTP SERVER (ManagementServerProperties)
management:
  context-path: /system
  security:
    enabled: false
    role: ADMIN

endpoints:
  health:
    sensitive: false
  jmx:
    domain: PartyLootTracker
    uniqueNames: false
  jolokia:
    path: /jmx

jolokia:
  config:
    debug: true
